networks:
  magento-network:
    driver: bridge

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile  # 指定自訂 Dockerfile
    container_name: 'magento-php'
    volumes:
      - /data/enterprise:/data/enterprise
    environment:
      - PHP_MEMORY_LIMIT=2G
      - UPLOAD_MAX_FILESIZE=32M
      - POST_MAX_SIZE=32M
      - PHP_ERROR_REPORTING="E_ALL & ~E_DEPRECATED & ~E_NOTICE"
    depends_on:
      - redis
      - elasticsearch
    networks:
      - magento-network
    command: ["bash", "-c", "/usr/local/bin/set-permissions.sh && php-fpm"]

  web:
    image: 'nginx:latest'
    container_name: 'magento-web'
    ports:
      - '80:80'
    volumes:
      - /data/enterprise:/data/enterprise
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/enterprise.conf:/etc/nginx/sites-enabled/enterprise.conf
      - ./var/log:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - php
    networks:
      - magento-network

  redis:
    image: 'redis:latest'
    container_name: 'magento-redis'
    command: redis-server --requirepass mitac1234
    ports:
      - '6379:6379'
    volumes:
      - /data/redis:/data
    networks:
      - magento-network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.1'
    container_name: 'magento-elasticsearch'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch:/var/lib/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - magento-network